name: Build and Test

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential python-dev-is-python3 libagg-dev libpotrace-dev pkg-config
      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint the code using Pylint
        run: |
          pylint $(git ls-files '*.py')

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential python-dev-is-python3 libagg-dev libpotrace-dev pkg-config
      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pytest

  build_docker:
    runs-on: ubuntu-latest
    needs: [build, test]

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag mediagrapher:$(date +%s)
